# Generated by Django 3.2.7 on 2021-09-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='LastName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
