# Generated by Django 3.2.7 on 2021-09-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0003_alter_customers_photofilename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='DateOfJoining',
            field=models.DateField(null=True),
        ),
    ]
