# Generated by Django 3.2.7 on 2021-09-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0007_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='Status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
