# Generated by Django 3.2.7 on 2021-09-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0008_alter_customers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='Status',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
