# Generated by Django 3.2.7 on 2021-09-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0010_customers_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='Group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
